### PR TITLE
fix formatter when exception is missing

### PR DESCRIPTION
**Pull request by digitalkaoz**
sorry, it seems we missed a case, tested it again in a real world application

### CODE REVIEW

**Comment by digitalkaoz** [comment]
@terrycain willing to merge this too? I also added more test cases

**Comment by terrycain** [comment]
Yeah, sorry been busy, will look over it tomorrow :smile:

**Comment by terrycain** [comment]
Nice looks good

**Comment by digitalkaoz** [comment]
thanks man, working like a charm now! Finally usable Cloudwatch Logs (they have automatic parsing for JSON logs)

**Comment by terricain** [comment]
Yup, CWLogs is pretty nice

**Pull request merged**
